hithitcrit/hithitcrit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/home/')),
    url(r'^home/', include('home.urls')),
    url(r'^viewer/', include('viewer.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hithitcrit/home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.home, name='home'),
]

hithitcrit/viewer/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?i)name/(?P<slug>[\w-]+)/$', views.objects_by_name, name='objects-by-name'),
    url(r'^(?i)pilots/$', views.pilot_grid, name='pilot-grid'),
    url(r'^(?i)upgrades/$', views.upgrade_grid, name='upgrade-grid'),
    url(r'^(?i)pilots/(?P<slug>[\w-]+)/$', views.pilot_details, name='pilot-details'),
    url(r'^(?i)upgrades/(?P<slug>[\w-]+)/$', views.upgrade_details, name='upgrade-details'),
    url(r'^(?i)ship/(?P<slug>[\w-]+)/$', views.ship_details, name='ship-details'),
    url(r'^(?i)faction/(?P<slug>[\w-]+)/$', views.faction_details, name='faction-details'),
    url(r'^(?i)primary-faction/(?P<slug>[\w-]+)/$', views.primary_faction_details, name='primary-faction-details'),
    url(r'^(?i)slot/(?P<slug>[\w-]+)/$', views.slot_details, name='slot-details'),
    url(r'^(?i)conditions/(?P<slug>[\w-]+)/$', views.condition_details, name='condition-details'),
    url(r'^(?i)sources/(?P<slug>[\w-]+)/$', views.source_details, name='source-details'),
]

hithitcrit/xwingdata/models/pilot.py
import itertools

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.template.defaultfilters import slugify
from django.urls import reverse

from .definition import Faction, Slot
from .ship import Ship
from .condition import Condition

class Pilot(models.Model):
    """Schema for pilots data file"""

    name = models.CharField(max_length=255)
    """The model's name as written on the card itself."""
    unique = models.BooleanField(default=False)
    """Indicates whether this pilot has a unique name or not.
    Some pilot cards have unique names, which are identified by the bullet to the left of the name.
    A player cannot field two or more cards that share the same unique name, even if those cards are of different types.
    """
    ship = models.ForeignKey(Ship, on_delete=models.CASCADE)
    """The pilot's ship name."""
    skill = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(9)])
    """The pilot's skill."""
    skill_special_ruling = models.BooleanField(default=False)
    """Having '?' as a pilot's skill means that there is a special ruling for it and it's variable."""
    points = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    """This pilot's squad points cost."""
    points_special_ruling = models.BooleanField(default=False)
    """Having '?' as a pilot's squad points cost means that there is a special ruling for it and it's variable."""
    slots = models.ManyToManyField(Slot, through='PilotSlot')
    """A list of the slots available to this pilot."""
    text = models.CharField(max_length=255, blank=True)
    """The pilot card's text describing its effect."""
    image = models.ImageField(upload_to="pilots/", blank=True)
    "The file path for this pilot card's image."
    faction = models.ForeignKey(Faction, on_delete=models.CASCADE)
    """The pilot's faction."""
    xws = models.CharField(max_length=255)
    """The pilot's unique XWS id as described in the XWS format."""
    attack_override = models.IntegerField(default=0, blank=True, null=True, validators=[MinValueValidator(0)])
    """The ship's attack value."""
    agility_override = models.IntegerField(default=0, blank=True, null=True, validators=[MinValueValidator(0)])
    """The ship's agility value."""
    hull_override = models.IntegerField(default=0, blank=True, null=True, validators=[MinValueValidator(0)])
    """The ship's hull value."""
    shields_override = models.IntegerField(default=0, blank=True, null=True, validators=[MinValueValidator(0)])
    """The ship's shields value."""
    range = models.CharField(max_length=255, blank=True, validators=[RegexValidator(regex='^[1-5](-[1-5])?$')])
    """The ship's range. This property is for huge ships only."""
    conditions = models.ManyToManyField(Condition, blank=True)
    """The pilot's related conditions."""
    slug = models.SlugField(unique=True)
    name_slug = models.SlugField()

    def __str__(self):
        return "{0} {1} {2} ({3})".format(self.faction, self.ship, self.name, self.xws)

    def save(self, *args, **kwargs):
        self.slug = self.name_slug = slugify(self.name)

        # name not unique so might need to add -1, -2 to slug
        for x in itertools.count(1):
            if not Pilot.objects.filter(slug=self.slug).exists():
                break
            self.slug = "{0}-{1}".format(self.name_slug, x)

        super(Pilot, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pilot-details', kwargs={"slug": self.slug})

    class Meta:
        unique_together = ('ship', 'faction', 'xws',)

class PilotSlot(models.Model):
    pilot = models.ForeignKey(Pilot)
    slot = models.ForeignKey(Slot)
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])

    def __str__(self):
        if self.quantity > 1:
            return "{0}: {1} (x{2})".format(self.pilot, self.slot, self.quantity)
        else:
            return "{0}: {1}".format(self.pilot, self.slot)

    class Meta:
        unique_together = ('pilot', 'slot', )

hithitcrit/xwingdata/models/source.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.template.defaultfilters import slugify
from django.urls import reverse

from .ship import Ship
from .pilot import Pilot
from .upgrade import Upgrade
from .condition import Condition

class Source(models.Model):
    name = models.CharField(max_length=255, unique=True)
    """The source's name as written on the package."""
    image = models.ImageField(upload_to="sources/", blank=True)
    """The file path for this pilot card's image."""
    thumb = models.ImageField(upload_to="sources/", blank=True)
    """The file path for this source's thumbnail."""
    wave = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(0)])
    """The sources wave (or product line)."""
    special_wave_name = models.CharField(null=True, blank=True, max_length=255)
    """Some sources are not grouped under particular wave, but under a particular product line
       When that's the case, use text for that type."""
    released = models.BooleanField(default=False)
    """This value indicates whether this sources has been released or not."""
    sku = models.CharField(unique=True, max_length=100, validators=[RegexValidator('^SWX[0-9]+$')])
    """Fantasy Flight Games unique product key for this particular source."""
    announcement_date = models.DateField()
    """Indicates the date on which the source was announced."""
    release_date = models.DateField(blank=True, null=True)
    """Indicates the date on which the source was released."""
    slug = models.SlugField(unique=True)
    
    """Contents"""
    ships = models.ManyToManyField(Ship, through='SourceShip')
    pilots = models.ManyToManyField(Pilot, through='SourcePilot')
    upgrades = models.ManyToManyField(Upgrade, through='SourceUpgrade')
    conditions = models.ManyToManyField(Condition, through='SourceCondition')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Source, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('source-details', kwargs={"slug": self.slug})

class SourceShip(models.Model):
    source = models.ForeignKey(Source)
    ship = models.ForeignKey(Ship)
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])

    def __str__(self):
        if self.quantity > 1:
            return "{0}: {1} (x{2})".format(self.source, self.ship, self.quantity)
        else:
            return "{0}: {1}".format(self.source, self.ship)

    class Meta:
        unique_together = ('source', 'ship')

class SourcePilot(models.Model):
    source = models.ForeignKey(Source)
    pilot = models.ForeignKey(Pilot)
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])

    def __str__(self):
        if self.quantity > 1:
            return "{0}: {1} (x{2})".format(self.source, self.pilot, self.quantity)
        else:
            return "{0}: {1}".format(self.source, self.pilot)

    class Meta:
        unique_together = ('source', 'pilot')

class SourceUpgrade(models.Model):
    source = models.ForeignKey(Source)
    upgrade = models.ForeignKey(Upgrade)
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])

    def __str__(self):
        if self.quantity > 1:
            return "{0}: {1} (x{2})".format(self.source, self.upgrade, self.quantity)
        else:
            return "{0}: {1}".format(self.source, self.upgrade)

    class Meta:
        unique_together = ('source', 'upgrade')

class SourceCondition(models.Model):
    source = models.ForeignKey(Source)
    condition = models.ForeignKey(Condition)
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])

    def __str__(self):
        if self.quantity > 1:
            return "{0}: {1} (x{2})".format(self.source, self.condition, self.quantity)
        else:
            return "{0}: {1}".format(self.source, self.condition)

    class Meta:
        unique_together = ('source', 'condition')

hithitcrit/xwingdata/models/upgrade.py
import itertools

from django.db import models
from django.core.validators import MinValueValidator, RegexValidator
from django.template.defaultfilters import slugify
from django.urls import reverse

from .definition import Action, Faction, Size, Slot
from .ship import Ship
from .condition import Condition

class Upgrade(models.Model):
    name = models.CharField(max_length=255)
    """The model's name as written on the card itself."""
    slot = models.ForeignKey(Slot)
    """The slots type used by this upgrade."""
    slot_cost = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    """Number of slots required to equip this upgrade"""
    points = models.IntegerField(null=False)
    """Squad points cost for this upgrade."""
    attack = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(1)]) 
    """The upgrade's attack value."""
    range = models.CharField(max_length=255, blank=True, validators=[RegexValidator(regex='^[1-5](-[1-5])?$')])
    """The upgrade's range. Usually attack related."""
    text = models.CharField(max_length=512)
    """The upgrade's text as written on the card."""
    image = models.ImageField(upload_to="upgrade/", blank=True)
    """The file path for this upgrade's image."""
    xws = models.CharField(max_length=255)
    """The upgrade's unique XWS id as described in the XWS format."""
    unique = models.BooleanField(default=False)
    """Some upgrade cards have unique names, which are identified by the bullet to the left of the name.
    A player cannot field two or more cards that share the same unique name, even if those cards are of different types.
    """
    size = models.ManyToManyField(Size, blank=True)
    """The ship sizes this upgrade is restricted to."""
    effect = models.CharField(max_length=255, blank=True)
    """Some upgrades have effects, like bomb tokens.
    The text for such effects go here."""
    faction = models.ForeignKey(Faction, null=True, blank=True)
    """The factions this upgrade is restricted to."""
    limited = models.BooleanField(default=False)
    """Indicates if this upgrade has the Limited trait.
    A ship cannot equip more than one copy of the same card with the Limited trait.
    """
    energy = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(0)])
    """The upgrade's energy cost"""
    grants_attack = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(1)]) 
    """Attack bonus granted by this upgrade"""
    grants_agility = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(1)]) 
    """Agility bonus granted by this upgrade"""
    grants_hull = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(1)]) 
    """Hull bonus granted by this upgrade"""
    grants_shields = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(1)]) 
    """Shield bonus granted by this upgrade"""
    grants_skill = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(1)]) 
    """Skill bonus granted by this upgrade"""
    grants_slot = models.ManyToManyField(Slot, through='GrantsSlot', related_name='grants') 
    """The slots granted by this upgrade"""
    grants_action = models.ManyToManyField(Action) 
    """The actions granted by this upgrade"""
    ship = models.ManyToManyField(Ship, blank=True)
    """The ships this upgrade is restricted to."""
    conditions = models.ManyToManyField(Condition, blank=True)
    """The upgrades's related conditions."""
    slug = models.SlugField(unique=True)
    name_slug = models.SlugField()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = self.name_slug = slugify(self.name)

        # name not unique so might need to add -1, -2 to slug
        for x in itertools.count(1):
            if not Upgrade.objects.filter(slug=self.slug).exists():
                break
            self.slug = "{0}-{1}".format(self.name_slug, x)

        super(Upgrade, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('upgrade-details', kwargs={"slug": self.slug})

    class Meta:
        unique_together = ('name', 'faction',)

class GrantsSlot(models.Model):
    upgrade = models.ForeignKey(Upgrade)
    slot = models.ForeignKey(Slot)
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])

    def __str__(self):
        if self.quantity > 1:
            return "{0}: {1} (x{2})".format(self.upgrade, self.slot, self.quantity)
        else:
            return "{0}: {1}".format(self.upgrade, self.slot)

    class Meta:
        unique_together = ('upgrade', 'slot', )

hithitcrit/viewer/templates/condition_details.html
{% extends "base_template.html" %}
{% load static %}

{% block title %}
<title>{{ condition.name }}</title>
{% endblock %}

{% block header %}
<link rel="stylesheet" type="text/css" href="{% static "viewer/expanded_details.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "viewer/grid.css" %}">
{% endblock %}

{% block content %}
{% include "expanded_condition.html" %}
{% endblock %}

hithitcrit/viewer/templates/expanded_condition.html
<div class="card">
  <div class="cardimage">
    {% if condition.image %}
    <img src="{{ condition.image.url }}"/>
    {% endif %}
  </div>
  <div class="expandedinformation">
    <div><span class="bold">Name:</span> {{ condition.name }}</div>
    <div><span class="bold">Unique:</span> {{ condition.unique }}</div>
    <div><span class="bold">Found in:</span> {% for source in condition.source_set.all %}<div><a href="{{ source.get_absolute_url }}">{{ source.name }}</a></div>{% endfor %}</div>
    <div><span class="bold">Text:</span> {{ condition.text }}</div>
    <div><span class="bold">Pilots:</span> {% for pilot in condition.pilot_set.all %}<div><a href="{{ pilot.get_absolute_url }}">{{ pilot.name }}</a></div>{% endfor %}</div>
    <div><span class="bold">Upgrades:</span> {% for upgrade in condition.upgrade_set.all %}<div><a href="{{ upgrade.get_absolute_url }}">{{ upgrade.name }}</a></div>{% endfor %}</div>
  </div>
</div>

hithitcrit/viewer/templates/expanded_pilot.html
<div class="card">
  <div class="cardimage">
    {% if pilot.image %}
    <a href="{{ pilot.get_absolute_url }}"><img src="{{ pilot.image.url }}"/></a>
    {% endif %}
  </div>
  <div class="expandedinformation">
    <div><span class="bold">Name:</span> <a href="{% url 'objects-by-name' slug=pilot.name_slug %}">{{ pilot.name }}</a></div>
    <div><span class="bold">Unique:</span> {{ pilot.unique }}</div>
    <div><span class="bold">Ship:</span> <a href="{{ pilot.ship.get_absolute_url }}">{{ pilot.ship.name }}</a></div>
    <div><span class="bold">Faction:</span> <a href="{{ pilot.faction.get_absolute_url }}">{{ pilot.faction.name }}</a> (<a href="{{ pilot.faction.primary_faction.get_absolute_url }}">{{ pilot.faction.primary_faction.name }}</a>)</div>
    <div><span class="bold">Skill:</span> {% if pilot.skill_special_ruling %}*{% else %}{{ pilot.skill }}{% endif %}</div>
    <div><span class="bold">Points:</span> {% if pilot.points_special_ruling %}-{% else %}{{ pilot.points }}{% endif %}</div>
    {% if pilot.ship.epic_points %}
    <div><span class="bold">Epic points:</span> {{ pilot.ship.epic_points }}</div>
    {% endif %}
    {% if pilot.ship.attack or pilot.attack_override %}
    <div><span class="bold">Attack:</span> {% if pilot.attack_override %}{{ pilot.attack_override }}{% else %}{{ pilot.ship.attack }}{% endif %}</div>
    {% endif %}
    {% if pilot.range != "" %}
    <div><span class="bold">Range:</span> {{ pilot.range }}</div>
    {% endif %}
    {% if pilot.ship.energy %}
    <div><span class="bold">Energy:</span> {{ pilot.ship.energy }}</div>
    {% endif %}
    <div><span class="bold">Agility:</span> {% if pilot.agility_override %}{{ pilot.agility_override }}{% else %}{{ pilot.ship.agility }}{% endif %}</div>
    <div><span class="bold">Hull:</span> {% if pilot.hull_override %}{{ pilot.hull_override }}{% else %}{{ pilot.ship.hull }}{% endif %}</div>
    <div><span class="bold">Shields:</span> {% if pilot.shields_override %}{{ pilot.shields_override }}{% else %}{{ pilot.ship.shields }}{% endif %}</div>
    <div><span class="bold">Slots:</span> {% for slot in pilot.pilotslot_set.all %}<a href="{{ slot.slot.get_absolute_url }}">{{ slot.slot.name }}</a>{% if slot.quantity > 1 %} (x{{ slot.quantity }}){% endif %}{% if not forloop.last %}, {% endif %}{% endfor %}</div>
    <div><span class="bold">Actions:</span> {% for action in pilot.ship.actions.all %}{{ action.action }}{% if not forloop.last %}, {% endif %}{% endfor %}</div>
    {% if pilot.conditions.all %}
    <div><span class="bold">Conditions:</span> {% for condition in pilot.conditions.all %}<a href="{{ condition.get_absolute_url }}">{{ condition.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</div>
    {% endif %}
    {% if pilot.text %}
    <div><span class="bold">Text:</span> {{ pilot.text }}</div>
    {% endif %}
    <div><span class="bold">Found in:</span> {% for sourcepilot in pilot.sourcepilot_set.all %}<div><a href="{{ sourcepilot.source.get_absolute_url }}">{{ sourcepilot.source.name }}</a>{% if sourcepilot.quantity > 1 %} (x{{ sourcepilot.quantity }}){% endif %}</div>{% endfor %}</div>
  </div>
</div>

hithitcrit/viewer/templates/expanded_ship.html
  <div class="card">
    <div class="expandedinformation">
      <div><span class="bold">Name:</span> <a href="{{ ship.get_absolute_url }}">{{ ship.name }}</a></div>
      <div><span class="bold">Faction:</span> {% for faction in ship.faction.all %}<a href="{{ faction.get_absolute_url }}">{{ faction.name }}</a>(<a href="{{ faction.primary_faction.get_absolute_url }}">{{ faction.primary_faction.name }}</a>){% if not forloop.last %}, {% endif %}{% endfor %} </div>
      <div><span class="bold">Points:</span> </div>
      {% if ship.epic_points %}
      <div><span class="bold">Epic points:</span> {{ ship.epic_points }}</div>
      {% endif %}
      {% if ship.attack %}
      <div><span class="bold">Attack:</span> {{ ship.attack }}</div>
      {% endif %}
      {% if ship.energy %}
      <div><span class="bold">Energy:</span> {{ ship.energy }}</div>
      {% endif %}
      <div><span class="bold">Agility:</span> {{ ship.agility }}</div>
      <div><span class="bold">Hull:</span> {{ ship.hull }}</div>
      <div><span class="bold">Shields:</span> {{ ship.shields }}</div>
      <div><span class="bold">Slots:</span> </div>
      <div><span class="bold">Actions:</span> {% for action in ship.actions.all %}{{ action.action }}{% if not forloop.last %}, {% endif %}{% endfor %} </div>
      <div><span class="bold">Found in:</span> {% for sourceship in ship.sourceship_set.all %}<div><a href="{{ sourceship.source.get_absolute_url }}">{{ sourceship.source.name }}</a>{% if sourceship.quantity > 1 %} (x{{ sourceship.quantity }}){% endif %}</div>{% endfor %}</div>
    </div>
  </div>

hithitcrit/viewer/templates/expanded_source.html
<div class="card">
  <div class="cardimage">
    {% if source.image %}
    <img src="{{ source.image.url }}"/>
    {% endif %}
  </div>
  <div class="expandedinformation">
    <div><span class="bold">Name:</span> {{ source.name }}</div>
    <div><span class="bold">Ships:</span> {% for sourcesship in source.sourceship_set.all %}<div><a href="{{ sourcesship.ship.get_absolute_url }}">{{ sourcesship.ship.name }}</a>{% if sourcesship.quantity > 1 %} (x{{ sourcesship.quantity }}){% endif %}</div>{% endfor %}</div>
    <div><span class="bold">Pilots:</span> {% for sourcepilot in source.sourcepilot_set.all %}<div><a href="{{ sourcepilot.pilot.get_absolute_url }}">{{ sourcepilot.pilot.name }}</a>{% if sourcepilot.quantity > 1 %} (x{{ sourcepilot.quantity }}){% endif %}</div>{% endfor %}</div>
    <div><span class="bold">Upgrades:</span> {% for sourceupgrade in source.sourceupgrade_set.all %}<div><a href="{{ sourceupgrade.upgrade.get_absolute_url }}">{{ sourceupgrade.upgrade.name }}</a>{% if sourceupgrade.quantity > 1 %} (x{{ sourceupgrade.quantity }}){% endif %}</div>{% endfor %}</div>
    {% if source.conditions.all %}
    <div><span class="bold">Conditions:</span> {% for sourcecondition in source.sourcecondition_set.all %}<div><a href="{{ sourcecondition.condition.get_absolute_url }}">{{ sourcecondition.condition.name }}</a>{% if sourcecondition.quantity > 1 %} (x{{ sourcecondition.quantity }}){% endif %}</div>{% endfor %}</div>
    {% endif %}
  </div>
</div>

hithitcrit/viewer/templates/expanded_upgrade.html
<div class="card">
  <div class="cardimage">
    {% if upgrade.image %}
    <img src="{{ upgrade.image.url }}"/>
    {% endif %}
  </div>
  <div class="expandedinformation">
    <div><span class="bold">Name:</span> <a href="{% url 'objects-by-name' slug=upgrade.slug %}">{{ upgrade.name }}</a></div>
    <div><span class="bold">Unique:</span> {{ upgrade.unique }}</div>
    <div><span class="bold">Limited:</span> {{ upgrade.limited }}</div>
    {% if upgrade.faction %}
    <div><span class="bold">Faction:</span> {{ upgrade.faction }}</div>
    {% endif %}
    {% if upgrade.ship.all %}
    <div><span class="bold">Ship:</span> {% for ship in upgrade.ship.all %}<a href="{{ ship.get_absolute_url }}">{{ ship.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</div>
    {% endif %}
    {% if upgrade.size.all %}
    <div><span class="bold">Size:</span> {% for size in upgrade.size.all %}{{ size.size }}{% if not forloop.last %}, {% endif %}{% endfor %}</div>
    {% endif %}
    <div><span class="bold">Slot:</span> <a href="{{ upgrade.slot.get_absolute_url }}">{{ upgrade.slot.name }}</a>{% if upgrade.slot_cost > 1 %} (x{{ upgrade.slot_cost }}){% endif %}</div>
    <div><span class="bold">Points:</span> {{ upgrade.points }}</div>
    {% if upgrade.energy %}
    <div><span class="bold">Energy cost:</span> {{ upgrade.energy }}</div>
    {% endif %}
    {% if upgrade.attack %}
    <div><span class="bold">Attack:</span> {{ upgrade.attack }}</div>
    {% endif %}
    {% if upgrade.range != "" %}
    <div><span class="bold">Range:</span> {{ upgrade.range }}</div>
    {% endif %}
    <div><span class="bold">Text:</span> {{ upgrade.text }}</div>
    {% if upgrade.effect != "" %}
    <div><span class="bold">Effect:</span> {{ upgrade.effect }}</div>
    {% endif %}
    {% if upgrade.grants_attack %}
    <div><span class="bold">Grants attack:</span> {% if upgrade.grants_attack > 0 %}+{% endif %}{{ upgrade.grants_attack }}</div>
    {% endif %}
    {% if upgrade.grants_agility %}
    <div><span class="bold">Grants agility:</span> {% if upgrade.grants_agility > 0 %}+{% endif %}{{ upgrade.grants_agility }}</div>
    {% endif %}
    {% if upgrade.grants_hull %}
    <div><span class="bold">Grants hull:</span> {% if upgrade.grants_hull > 0 %}+{% endif %}{{ upgrade.grants_hull }}</div>
    {% endif %}
    {% if upgrade.grants_shields %}
    <div><span class="bold">Grants shields:</span> {% if upgrade.grants_shields > 0 %}+{% endif %}{{ upgrade.grants_shields }}</div>
    {% endif %}
    {% if upgrade.grants_skill %}
    <div><span class="bold">Grants skill:</span> {% if upgrade.grants_skill > 0 %}+{% endif %}{{ upgrade.grants_skill }}</div>
    {% endif %}
    {% if upgrade.grantsslot_set.all %}
    <div><span class="bold">Grants slot:</span> {% for grant in upgrade.grantsslot_set.all %}<a href="{{ grant.slot.get_absolute_url }}">{{ grant.slot.name }}</a>{% if grant.quantity > 1 %} (x{{ grant.quantity }}){% endif %}{% if not forloop.last %}, {% endif %}{% endfor %}</div>
    {% endif %}
    {% if upgrade.grants_action.all %}
    <div><span class="bold">Grants action:</span> {% for action in upgrade.grants_action.all %}{{ action.action }}{% if not forloop.last %}, {% endif %}{% endfor %}</div>
    {% endif %}
    {% if upgrade.conditions.all %}
    <div><span class="bold">Conditions:</span> {% for condition in upgrade.conditions.all %}<a href="{{ condition.get_absolute_url }}">{{ condition.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</div>
    {% endif %}
    <div><span class="bold">Found in:</span> {% for sourceupgrade in upgrade.sourceupgrade_set.all %}<div><a href="{{ sourceupgrade.source.get_absolute_url }}">{{ sourceupgrade.source.name }}</a>{% if sourceupgrade.quantity > 1 %} (x{{ sourceupgrade.quantity }}){% endif %}</div>{% endfor %}</div>
  </div>
</div>